// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using file_upload.Data;

namespace file_upload.Migrations
{
    [DbContext(typeof(FileUploadContext))]
    [Migration("20220418163041_init")]
    partial class init
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 64)
                .HasAnnotation("ProductVersion", "5.0.10");

            modelBuilder.Entity("file_upload.Data.file", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Bucket")
                        .HasColumnType("text");

                    b.Property<string>("Location")
                        .HasColumnType("text");

                    b.Property<string>("filename")
                        .HasColumnType("text");

                    b.Property<string>("key")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("file");
                });
#pragma warning restore 612, 618
        }
    }
}
